-- Seed data for complaints
INSERT INTO public.complaints (id, title, title_hi, description, description_hi, category, category_hi, priority, status, department_id, latitude, longitude, area, citizen_id, citizen_name, citizen_phone, image_url, ai_summary, ai_summary_hi, ai_confidence, trust_analysis, trust_score, assigned_officer)
VALUES
  (
    'JM-2026-001-999', 
    'Massive garbage pile near bus stand', 
    'बस स्टैंड के पास भारी कचरे का ढेर', 
    'There is a huge pile of garbage that has not been collected for a week. The smell is unbearable and it is becoming a health hazard.', 
    'बस स्टैंड के पास एक सप्ताह से कचरा नहीं उठाया गया है। बदबू असहनीय है और यह स्वास्थ्य के लिए खतरा बन रहा है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'high', 
    'department_assigned', 
    'nagar-nigam', 
    26.85, 
    80.95, 
    'Alambagh, Lucknow', 
    'user-1', 
    'Aman Singh', 
    '+91 98765 43210', 
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&h=400&fit=crop', 
    'Severe sanitation hazard reported near Alambagh bus stand.', 
    'आलमबाग बस स्टैंड के पास गंभीर स्वच्छता खतरा।', 
    0.95, 
    '{"trustLevel":"high","spamProbability":0.05}'::jsonb, 
    0.95, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-002-888', 
    'Street light not working in sector 4', 
    'सेक्टर 4 में स्ट्रीट लाइट काम नहीं कर रही', 
    'Street light has been broken for 3 days, causing accidents in the dark.', 
    '3 दिन से स्ट्रीट लाइट खराब है, जिससे अंधेरे में दुर्घटनाएं हो रही हैं।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'medium', 
    'resolved', 
    'lmc', 
    26.84, 
    80.96, 
    'Gomti Nagar, Lucknow', 
    'user-2', 
    'Priya Verma', 
    '+91 87654 32109', 
    'https://images.unsplash.com/photo-1517789490516-fb46487e49ba?w=600&h=400&fit=crop', 
    'Street light outage reported in Gomti Nagar.', 
    'गोमती नगर में स्ट्रीट लाइट खराब होने की रिपोर्ट।', 
    0.92, 
    '{"trustLevel":"high","spamProbability":0.02}'::jsonb, 
    0.98, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-003-777', 
    'Major water pipe burst on Main Road', 
    'मुख्य मार्ग पर पानी की पाइपलाइन फटी', 
    'A major water pipeline has burst, causing severe waterlogging and wastage of clean drinking water.', 
    'एक प्रमुख पानी की पाइपलाइन फट गई है, जिससे भारी जलभराव और पीने के साफ पानी की बर्बादी हो रही है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'high', 
    'submitted', 
    'jal-nigam', 
    26.86, 
    80.94, 
    'Hazratganj, Lucknow', 
    'user-3', 
    'Rahul Sharma', 
    '+91 91234 56780', 
    'https://images.unsplash.com/photo-1541888075765-a81062b08a54?w=600&h=400&fit=crop', 
    'Major pipeline burst causing waterlogging in Hazratganj.', 
    'हजरतगंज में पाइपलाइन फटने से जलभराव की समस्या।', 
    0.96, 
    '{"trustLevel":"high","spamProbability":0.01}'::jsonb, 
    0.99, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-004-666', 
    'Pothole causing accidents', 
    'गड्ढे के कारण हो रही दुर्घटनाएं', 
    'Large pothole in the middle of the road has caused two bike accidents today alone. Please fix urgently.', 
    'सड़क के बीच में बड़े गड्ढे के कारण आज ही दो बाइक दुर्घटनाएं हुई हैं। कृपया तत्काल ठीक करें।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'high', 
    'department_assigned', 
    'pwd', 
    26.87, 
    80.93, 
    'Indira Nagar, Lucknow', 
    'user-4', 
    'Sneha Gupta', 
    '+91 99887 76655', 
    'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&h=400&fit=crop', 
    'Dangerous pothole causing accidents in Indira Nagar.', 
    'इंदिरा नगर में गड्ढे के कारण दुर्घटनाओं की रिपोर्ट।', 
    0.94, 
    '{"trustLevel":"high","spamProbability":0.04}'::jsonb, 
    0.96, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-005-555', 
    'Stray dogs attacking pedestrians', 
    'आवारा कुत्ते राहगीरों पर हमला कर रहे हैं', 
    'A pack of stray dogs is acting aggressively and has bitten a child yesterday. Immediate action required.', 
    'आवारा कुत्तों का एक झुंड आक्रामक हो रहा है और कल एक बच्चे को काट लिया है। तत्काल कार्रवाई की आवश्यकता है।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'medium', 
    'submitted', 
    'health-dept', 
    26.855, 
    80.965, 
    'Mahanagar, Lucknow', 
    'user-5', 
    'Vikram Singh', 
    '+91 88776 65544', 
    'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=600&h=400&fit=crop', 
    'Aggressive stray dogs reported in Mahanagar.', 
    'महानगर में आक्रामक आवारा कुत्तों की शिकायत।', 
    0.88, 
    '{"trustLevel":"medium","spamProbability":0.1}'::jsonb, 
    0.85, 
    'Dr. Sanjay Pandey'
  ),
  (
    'JM-2026-006-444', 
    'Open manhole on footpath', 
    'फुटपाथ पर खुला मैनहोल', 
    'The manhole cover is missing near the park gate. It is very dangerous for children playing nearby.', 
    'पार्क के गेट के पास मैनहोल का ढक्कन गायब है। यह पास में खेलने वाले बच्चों के लिए बहुत खतरनाक है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'high', 
    'resolved', 
    'nagar-nigam', 
    26.845, 
    80.935, 
    'Aashiana, Lucknow', 
    'user-6', 
    'Kavita Tiwari', 
    '+91 77665 54433', 
    'https://images.unsplash.com/photo-1621245781440-101f3db3e6ba?w=600&h=400&fit=crop', 
    'Dangerous open manhole near park in Aashiana.', 
    'आशियाना में पार्क के पास खतरनाक खुला मैनहोल।', 
    0.97, 
    '{"trustLevel":"high","spamProbability":0.01}'::jsonb, 
    0.99, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-007-333', 
    'Illegal construction blocking drain', 
    'अवैध निर्माण से नाला बंद', 
    'Someone is building a ramp over the public drain, which is causing sewage water to overflow onto the street.', 
    'कोई सार्वजनिक नाले के ऊपर रैंप बना रहा है, जिससे सीवर का पानी सड़क पर बह रहा है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'low', 
    'department_assigned', 
    'municipal-authority', 
    26.835, 
    80.955, 
    'Rajajipuram, Lucknow', 
    'user-7', 
    'Mohammad Arif', 
    '+91 66554 43322', 
    'https://images.unsplash.com/photo-1504307651254-35680f356f12?w=600&h=400&fit=crop', 
    'Drain blocked by illegal construction in Rajajipuram.', 
    'राजाजीपुरम में अवैध निर्माण के कारण नाला अवरुद्ध।', 
    0.91, 
    '{"trustLevel":"high","spamProbability":0.08}'::jsonb, 
    0.92, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-008-222', 
    'Dead animal on the road', 
    'सड़क पर मृत जानवर', 
    'A dead cow is lying on the bypass road since morning. Please send a vehicle to pick it up.', 
    'सुबह से बाईपास रोड पर एक मृत गाय पड़ी है। कृपया इसे उठाने के लिए वाहन भेजें।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'medium', 
    'submitted', 
    'nagar-nigam', 
    26.88, 
    80.92, 
    'Jankipuram, Lucknow', 
    'user-8', 
    'Alok Pandey', 
    '+91 55443 32211', 
    'https://images.unsplash.com/photo-1596781206132-75ebdb5952d4?w=600&h=400&fit=crop', 
    'Dead animal removal requested in Jankipuram.', 
    'जानकीपुरम में मृत जानवर उठाने का अनुरोध।', 
    0.93, 
    '{"trustLevel":"high","spamProbability":0.03}'::jsonb, 
    0.97, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-009-111', 
    'Park poorly maintained', 
    'पार्क का रखरखाव खराब है', 
    'The swings in the local park are broken and the grass has not been cut for months.', 
    'स्थानीय पार्क में झूले टूटे हुए हैं और महीनों से घास नहीं काटी गई है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'low', 
    'resolved', 
    'nagar-nigam', 
    26.83, 
    80.96, 
    'Vikas Nagar, Lucknow', 
    'user-9', 
    'Neha Singh', 
    '+91 44332 21100', 
    'https://images.unsplash.com/photo-1500367215255-0e0b2148b556?w=600&h=400&fit=crop', 
    'Poor park maintenance and broken swings in Vikas Nagar.', 
    'विकास नगर में पार्क का खराब रखरखाव और टूटे झूले।', 
    0.85, 
    '{"trustLevel":"medium","spamProbability":0.15}'::jsonb, 
    0.8, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-010-000', 
    'Live electric wire hanging low', 
    'बिजली का खुला तार नीचे लटक रहा है', 
    'A live electric wire has snapped and is hanging dangerously low near the school gate. Highly dangerous!', 
    'एक खुला बिजली का तार टूट गया है और स्कूल के गेट के पास खतरनाक रूप से नीचे लटक रहा है। अत्यधिक खतरनाक!', 
    'Electricity', 
    'बिजली', 
    'high', 
    'department_assigned', 
    'power-dept', 
    26.865, 
    80.945, 
    'Chowk, Lucknow', 
    'user-10', 
    'Syed Ali', 
    '+91 33221 10099', 
    'https://images.unsplash.com/photo-1544257124-74bf5fbfe4b2?w=600&h=400&fit=crop', 
    'Dangerous live wire hanging near school in Chowk.', 
    'चौक में स्कूल के पास लटकता हुआ खतरनाक खुला तार।', 
    0.98, 
    '{"trustLevel":"high","spamProbability":0}'::jsonb, 
    1, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-011-100', 
    'Uncontrolled dumping behind Hazratganj Market', 
    'हजरतगंज बाजार के पीछे अनियंत्रित कूड़ा डंपिंग', 
    'Piles of plastic waste and food containers have accumulated behind the main shopping lane. It''s attracting pests and stray animals.', 
    'मुख्य शॉपिंग लेन के पीछे प्लास्टिक कचरे और खाद्य डिब्बों के ढेर जमा हो गए हैं। यह कीटों और आवारा जानवरों को आकर्षित कर रहा है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'high', 
    'submitted', 
    'nagar-nigam', 
    26.8447, 
    80.9442, 
    'Hazratganj, Lucknow', 
    'user-10', 
    'Abhishek Mishra', 
    '+91 9812345678', 
    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop', 
    'AI auto-summary for uncontrolled dumping behind hazratganj market in Hazratganj.', 
    'Hazratganj में हजरतगंज बाजार के पीछे अनियंत्रित कूड़ा डंपिंग का स्व-निर्मित सारांश।', 
    0.8, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-012-117', 
    'Overflowing public dustbins in Patrakar Puram', 
    'पत्रकार पुरम में सार्वजनिक डस्टबिन का ओवरफ्लो होना', 
    'The large green community dustbins near Patrakar Puram crossing have not been emptied for 4 days, resulting in waste spilling onto the main road.', 
    'पत्रकार पुरम चौराहे के पास बड़े हरे सामुदायिक डस्टबिन 4 दिनों से खाली नहीं किए गए हैं, जिससे कचरा मुख्य सड़क पर फैल रहा है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'medium', 
    'department_assigned', 
    'nagar-nigam', 
    26.855, 
    80.9745, 
    'Gomti Nagar, Lucknow', 
    'user-11', 
    'Rajesh Pandey', 
    '+91 9813580245', 
    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop', 
    'AI auto-summary for overflowing public dustbins in patrakar puram in Gomti Nagar.', 
    'Gomti Nagar में पत्रकार पुरम में सार्वजनिक डस्टबिन का ओवरफ्लो होना का स्व-निर्मित सारांश।', 
    0.81, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-013-134', 
    'Clogged open drain near Sector H market', 
    'सेक्टर एच बाजार के पास बंद खुला नाला', 
    'Garbage and plastic bottles have choked the open stormwater drain, causing dirty water to overflow onto the walking path.', 
    'कचरे और प्लास्टिक की बोतलों ने खुले तूफान के पानी के नाले को अवरुद्ध कर दिया है, जिससे गंदा पानी चलने वाले रास्ते पर बह रहा है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'high', 
    'officer_reviewing', 
    'nagar-nigam', 
    26.8819, 
    80.9319, 
    'Aliganj, Lucknow', 
    'user-12', 
    'Sunita Rao', 
    '+91 9814814812', 
    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop', 
    'AI auto-summary for clogged open drain near sector h market in Aliganj.', 
    'Aliganj में सेक्टर एच बाजार के पास बंद खुला नाला का स्व-निर्मित सारांश।', 
    0.83, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-014-151', 
    'Unattended municipal waste pile in Sector 14', 
    'सेक्टर 14 में लावारिस नगर निगम कचरे का ढेर', 
    'A large heap of dry leaves and household waste has been dumped at the corner of Sector 14 park, causing breathing issues for visiting elders.', 
    'सेक्टर 14 पार्क के कोने में सूखी पत्तियों और घरेलू कचरे का एक बड़ा ढेर लगा दिया गया है, जिससे आने वाले बुजुर्गों को सांस लेने में समस्या हो रही है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'low', 
    'resolved', 
    'nagar-nigam', 
    26.8867, 
    80.962, 
    'Indira Nagar, Lucknow', 
    'user-13', 
    'Fatima Zaidi', 
    '+91 9816049379', 
    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop', 
    'AI auto-summary for unattended municipal waste pile in sector 14 in Indira Nagar.', 
    'Indira Nagar में सेक्टर 14 में लावारिस नगर निगम कचरे का ढेर का स्व-निर्मित सारांश।', 
    0.84, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-015-168', 
    'Accumulated market waste blocking pedestrian path', 
    'पैदल पथ को अवरुद्ध करने वाला बाजार का संचित कचरा', 
    'Vegetable market refuse is dumped daily near the pavement. No municipal sweeper has cleaned the area since Monday.', 
    'सब्जी मंडी का कचरा रोजाना पटरी के पास फेंक दिया जाता है। सोमवार से किसी भी नगर निगम के सफाई कर्मचारी ने क्षेत्र की सफाई नहीं की है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'medium', 
    'submitted', 
    'nagar-nigam', 
    26.8431, 
    80.9247, 
    'Aminabad, Lucknow', 
    'user-14', 
    'Karan Johar', 
    '+91 9817283946', 
    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop', 
    'AI auto-summary for accumulated market waste blocking pedestrian path in Aminabad.', 
    'Aminabad में पैदल पथ को अवरुद्ध करने वाला बाजार का संचित कचरा का स्व-निर्मित सारांश।', 
    0.85, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-016-185', 
    'Contaminated muddy water supply in Vipul Khand', 
    'विपुल खंड में प्रदूषित मटमैले पानी की आपूर्ति', 
    'Residents of Vipul Khand are receiving highly turbid, brownish mud water in their taps, making it completely unfit for drinking or cooking.', 
    'विपुल खंड के निवासियों को अपने नलों में अत्यधिक गंदा, भूरे रंग का कीचड़ का पानी मिल रहा है, जिससे यह पीने या खाना पकाने के लिए पूरी तरह से अनुपयुक्त हो गया है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'high', 
    'department_assigned', 
    'jal-nigam', 
    26.8562, 
    80.9757, 
    'Gomti Nagar, Lucknow', 
    'user-15', 
    'Vikram Rathore', 
    '+91 9818518513', 
    'https://images.unsplash.com/photo-1581244904349-8e47cb23e59b?w=600&h=400&fit=crop', 
    'AI auto-summary for contaminated muddy water supply in vipul khand in Gomti Nagar.', 
    'Gomti Nagar में विपुल खंड में प्रदूषित मटमैले पानी की आपूर्ति का स्व-निर्मित सारांश।', 
    0.86, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-017-202', 
    'Low water pressure in Sector C block', 
    'सेक्टर सी ब्लॉक में पानी का कम दबाव', 
    'The municipal water supply pressure is extremely low, making it impossible to fill overhead tanks even with booster pumps.', 
    'नगर निगम की जलापूर्ति का दबाव बेहद कम है, जिससे बूस्टर पंपों के बाद भी ओवरहेड टैंकों को भरना असंभव हो गया है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'medium', 
    'officer_reviewing', 
    'jal-nigam', 
    26.8876, 
    80.9629, 
    'Indira Nagar, Lucknow', 
    'user-16', 
    'Divya Joshi', 
    '+91 9819753080', 
    'https://images.unsplash.com/photo-1581244904349-8e47cb23e59b?w=600&h=400&fit=crop', 
    'AI auto-summary for low water pressure in sector c block in Indira Nagar.', 
    'Indira Nagar में सेक्टर सी ब्लॉक में पानी का कम दबाव का स्व-निर्मित सारांश।', 
    0.88, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-018-219', 
    'Water pipeline leakage at Kapoorthala crossing', 
    'कपूरथला चौराहे पर पानी की पाइपलाइन लीक', 
    'A major joint leak in the main pipeline is spraying clean drinking water onto the street, flooding the lane and causing traffic delays.', 
    'मुख्य पाइपलाइन में एक बड़ा संयुक्त रिसाव सड़क पर पीने का साफ पानी बिखेर रहा है, जिससे गली में पानी भर गया है और यातायात में देरी हो रही है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'high', 
    'resolved', 
    'jal-nigam', 
    26.8834, 
    80.9334, 
    'Aliganj, Lucknow', 
    'user-17', 
    'Mohd Sajid', 
    '+91 9820987647', 
    'https://images.unsplash.com/photo-1581244904349-8e47cb23e59b?w=600&h=400&fit=crop', 
    'AI auto-summary for water pipeline leakage at kapoorthala crossing in Aliganj.', 
    'Aliganj में कपूरथला चौराहे पर पानी की पाइपलाइन लीक का स्व-निर्मित सारांश।', 
    0.89, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-019-236', 
    'Irregular water supply timings in Lalbagh', 
    'लालबाग में जलापूर्ति का अनियमित समय', 
    'Water is only supplied for 10-15 minutes daily at random morning hours, causing severe inconvenience to office-going residents.', 
    'पानी केवल 10-15 मिनट के लिए दैनिक रूप से सुबह के यादृच्छिक घंटों में आपूर्ति किया जाता है, जिससे कार्यालय जाने वाले निवासियों को गंभीर असुविधा होती है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'medium', 
    'submitted', 
    'jal-nigam', 
    26.8471, 
    80.9466, 
    'Hazratganj, Lucknow', 
    'user-18', 
    'Pradeep Sen', 
    '+91 9822222214', 
    'https://images.unsplash.com/photo-1581244904349-8e47cb23e59b?w=600&h=400&fit=crop', 
    'AI auto-summary for irregular water supply timings in lalbagh in Hazratganj.', 
    'Hazratganj में लालबाग में जलापूर्ति का अनियमित समय का स्व-निर्मित सारांश।', 
    0.9, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-020-253', 
    'Leaking water valve causing street waterlogging', 
    'सड़क पर जलभराव का कारण बना पानी का रिसाव वाल्व', 
    'The main pipeline control valve near Aminabad temple is leaking constantly, causing a huge puddle that damages the local road surface.', 
    'अमीनाबाद मंदिर के पास मुख्य पाइपलाइन नियंत्रण वाल्व लगातार लीक हो रहा है, जिससे एक बड़ा गड्ढा बन गया है जो स्थानीय सड़क की सतह को नुकसान पहुंचाता है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'low', 
    'department_assigned', 
    'jal-nigam', 
    26.8446, 
    80.9262, 
    'Aminabad, Lucknow', 
    'user-19', 
    'Pooja Vashisht', 
    '+91 9823456781', 
    'https://images.unsplash.com/photo-1581244904349-8e47cb23e59b?w=600&h=400&fit=crop', 
    'AI auto-summary for leaking water valve causing street waterlogging in Aminabad.', 
    'Aminabad में सड़क पर जलभराव का कारण बना पानी का रिसाव वाल्व का स्व-निर्मित सारांश।', 
    0.92, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Smt. Priya Sharma'
  ),
  (
    'JM-2026-021-270', 
    'Deep potholes on Sector 11 main street', 
    'सेक्टर 11 मुख्य मार्ग पर गहरे गड्ढे', 
    'Several deep potholes have formed on the main road, making commuting dangerous, especially for two-wheelers during night hours.', 
    'मुख्य सड़क पर कई गहरे गड्ढे बन गए हैं, जिससे यात्रा करना खतरनाक हो गया है, खासकर रात के समय दोपहिया वाहनों के लिए।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'high', 
    'officer_reviewing', 
    'pwd', 
    26.8888, 
    80.9641, 
    'Indira Nagar, Lucknow', 
    'user-20', 
    'Abhishek Mishra', 
    '+91 9824691348', 
    'https://images.unsplash.com/photo-1599740831119-072d5257af53?w=600&h=400&fit=crop', 
    'AI auto-summary for deep potholes on sector 11 main street in Indira Nagar.', 
    'Indira Nagar में सेक्टर 11 मुख्य मार्ग पर गहरे गड्ढे का स्व-निर्मित सारांश।', 
    0.93, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-022-287', 
    'Damaged asphalt on Kapoorthala main road', 
    'कपूरथला मुख्य मार्ग पर क्षतिग्रस्त डामर', 
    'The upper layer of the road has completely eroded, leaving sharp stones loose and creating severe dust pollution in the market area.', 
    'सड़क की ऊपरी परत पूरी तरह से नष्ट हो गई है, जिससे नुकीले पत्थर ढीले हो गए हैं और बाजार क्षेत्र में धूल का भारी प्रदूषण हो रहा है।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'medium', 
    'resolved', 
    'pwd', 
    26.8846, 
    80.9346, 
    'Aliganj, Lucknow', 
    'user-21', 
    'Rajesh Pandey', 
    '+91 9825925915', 
    'https://images.unsplash.com/photo-1599740831119-072d5257af53?w=600&h=400&fit=crop', 
    'AI auto-summary for damaged asphalt on kapoorthala main road in Aliganj.', 
    'Aliganj में कपूरथला मुख्य मार्ग पर क्षतिग्रस्त डामर का स्व-निर्मित सारांश।', 
    0.94, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-023-304', 
    'Caved-in road surface near GPO crossing', 
    'जीपीओ चौराहे के पास धंसी सड़क की सतह', 
    'A portion of the road surface has caved in near the GPO, creating a major traffic hazard. Needs immediate barricading and repair.', 
    'जीपीओ के पास सड़क की सतह का एक हिस्सा धंस गया है, जिससे यातायात को बड़ा खतरा हो गया है। तत्काल बैरिकेडिंग और मरम्मत की आवश्यकता है।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'high', 
    'submitted', 
    'pwd', 
    26.8483, 
    80.9478, 
    'Hazratganj, Lucknow', 
    'user-22', 
    'Sunita Rao', 
    '+91 9827160482', 
    'https://images.unsplash.com/photo-1599740831119-072d5257af53?w=600&h=400&fit=crop', 
    'AI auto-summary for caved-in road surface near gpo crossing in Hazratganj.', 
    'Hazratganj में जीपीओ चौराहे के पास धंसी सड़क की सतह का स्व-निर्मित सारांश।', 
    0.96, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-024-321', 
    'Uneven road patching near Manoj Pandey Chauraha', 
    'मनोज पांडे चौराहा के पास असमान सड़क पैचिंग', 
    'The road was patched after pipeline work but left uneven, causing vehicles to lose control at normal speed limits.', 
    'पाइपलाइन के काम के बाद सड़क को पैच किया गया था लेकिन असमान छोड़ दिया गया, जिससे वाहन सामान्य गति सीमा पर नियंत्रण खो रहे हैं।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'low', 
    'department_assigned', 
    'pwd', 
    26.8586, 
    80.9781, 
    'Gomti Nagar, Lucknow', 
    'user-23', 
    'Fatima Zaidi', 
    '+91 9828395049', 
    'https://images.unsplash.com/photo-1599740831119-072d5257af53?w=600&h=400&fit=crop', 
    'AI auto-summary for uneven road patching near manoj pandey chauraha in Gomti Nagar.', 
    'Gomti Nagar में मनोज पांडे चौराहा के पास असमान सड़क पैचिंग का स्व-निर्मित सारांश।', 
    0.97, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-025-338', 
    'Broken concrete slabs on market lane', 
    'बाजार की गली में टूटे कंक्रीट के स्लैब', 
    'The main market lane concrete road has cracked and broken, causing shoppers and older citizens to trip and fall regularly.', 
    'मुख्य बाजार की गली की कंक्रीट सड़क टूट गई है, जिससे खरीदार और वरिष्ठ नागरिक नियमित रूप से गिर रहे हैं।', 
    'Road Damage', 
    'सड़क मरम्मत / गड्ढे', 
    'medium', 
    'officer_reviewing', 
    'pwd', 
    26.8421, 
    80.9237, 
    'Aminabad, Lucknow', 
    'user-24', 
    'Karan Johar', 
    '+91 9829629616', 
    'https://images.unsplash.com/photo-1599740831119-072d5257af53?w=600&h=400&fit=crop', 
    'AI auto-summary for broken concrete slabs on market lane in Aminabad.', 
    'Aminabad में बाजार की गली में टूटे कंक्रीट के स्लैब का स्व-निर्मित सारांश।', 
    0.98, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Amit Verma'
  ),
  (
    'JM-2026-026-355', 
    'Frequent voltage fluctuations in Vivek Khand', 
    'विवेक खंड में बार-बार वोल्टेज में उतार-चढ़ाव', 
    'Severe voltage fluctuations are occurring multiple times a day, damaging home appliances like air conditioners and refrigerators.', 
    'विवेक खंड के निवासियों को अपने विद्युत कनेक्शनों में दैनिक बार-बार वोल्टेज का उतार-चढ़ाव मिल रहा है, जिससे उपकरण खराब हो रहे हैं।', 
    'Electricity', 
    'बिजली / विद्युत', 
    'high', 
    'resolved', 
    'power-dept', 
    26.8552, 
    80.9747, 
    'Gomti Nagar, Lucknow', 
    'user-25', 
    'Vikram Rathore', 
    '+91 9830864183', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop', 
    'AI auto-summary for frequent voltage fluctuations in vivek khand in Gomti Nagar.', 
    'Gomti Nagar में विवेक खंड में बार-बार वोल्टेज में उतार-चढ़ाव का स्व-निर्मित सारांश।', 
    0.81, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-027-372', 
    'Snapping of overhead cable in Sector J', 
    'सेक्टर जे में ओवरहेड केबल का टूटना', 
    'A secondary overhead power cable snapped and fell on the street. Fortunately, power was cut, but it needs urgent replacement.', 
    'एक सेकेंडरी ओवरहेड बिजली का तार टूटकर गली में गिर गया। सौभाग्य से, बिजली काट दी गई थी, लेकिन इसे तत्काल बदलने की आवश्यकता है।', 
    'Electricity', 
    'बिजली / विद्युत', 
    'high', 
    'submitted', 
    'power-dept', 
    26.8821, 
    80.9321, 
    'Aliganj, Lucknow', 
    'user-26', 
    'Divya Joshi', 
    '+91 9832098750', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop', 
    'AI auto-summary for snapping of overhead cable in sector j in Aliganj.', 
    'Aliganj में सेक्टर जे में ओवरहेड केबल का टूटना का स्व-निर्मित सारांश।', 
    0.82, 
    '{"trustLevel":"high","spamProbability":0.05,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.95, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-028-389', 
    'Sparking transformer near Janpath Market', 
    'जनपथ मार्केट के पास चिंगारी छोड़ता ट्रांसफार्मर', 
    'The commercial transformer is frequently sparking and emitting loud crackling noises, causing panic and temporary power outages.', 
    'व्यावसायिक ट्रांसफार्मर अक्सर चिंगारी छोड़ रहा है और तेज आवाजें निकाल रहा है, जिससे दहशत और अस्थायी बिजली कटौती हो रही है।', 
    'Electricity', 
    'बिजली / विद्युत', 
    'high', 
    'department_assigned', 
    'power-dept', 
    26.8458, 
    80.9453, 
    'Hazratganj, Lucknow', 
    'user-27', 
    'Mohd Sajid', 
    '+91 9833333317', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop', 
    'AI auto-summary for sparking transformer near janpath market in Hazratganj.', 
    'Hazratganj में जनपथ मार्केट के पास चिंगारी छोड़ता ट्रांसफार्मर का स्व-निर्मित सारांश।', 
    0.83, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-029-406', 
    'Unscheduled 6-hour power outage in Sector 18', 
    'सेक्टर 18 में बिना सूचना के 6 घंटे की बिजली कटौती', 
    'Residents are experiencing long power cuts daily without any prior notice or scheduled maintenance logs, affecting student studies.', 
    'निवासी बिना किसी पूर्व सूचना या निर्धारित रखरखाव लॉग के दैनिक रूप से लंबी बिजली कटौती का सामना कर रहे हैं, जिससे छात्रों की पढ़ाई प्रभावित हो रही है।', 
    'Electricity', 
    'बिजली / विद्युत', 
    'medium', 
    'officer_reviewing', 
    'power-dept', 
    26.8872, 
    80.9625, 
    'Indira Nagar, Lucknow', 
    'user-28', 
    'Pradeep Sen', 
    '+91 9834567884', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop', 
    'AI auto-summary for unscheduled 6-hour power outage in sector 18 in Indira Nagar.', 
    'Indira Nagar में सेक्टर 18 में बिना सूचना के 6 घंटे की बिजली कटौती का स्व-निर्मित सारांश।', 
    0.84, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-030-423', 
    'Low hanging high-tension wires in busy market', 
    'व्यस्त बाजार में नीचे लटकते हाई-टेंशन तार', 
    'HT electric wires are hanging extremely low, barely 8 feet above the commercial street, posing a major risk of electrocution.', 
    'एचटी बिजली के तार बेहद नीचे लटके हुए हैं, व्यावसायिक गली से बमुश्किल 8 फीट ऊपर, जिससे बिजली के झटके का बड़ा खतरा है।', 
    'Electricity', 
    'बिजली / विद्युत', 
    'high', 
    'resolved', 
    'power-dept', 
    26.8436, 
    80.9252, 
    'Aminabad, Lucknow', 
    'user-29', 
    'Pooja Vashisht', 
    '+91 9835802451', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop', 
    'AI auto-summary for low hanging high-tension wires in busy market in Aminabad.', 
    'Aminabad में व्यस्त बाजार में नीचे लटकते हाई-टेंशन तार का स्व-निर्मित सारांश।', 
    0.86, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Shri Vikram Singh'
  ),
  (
    'JM-2026-031-440', 
    'Dark street stretch behind GPO', 
    'जीपीओ के पीछे अंधेरा सड़क खंड', 
    'About 5 consecutive street light poles are non-functional, making the stretch completely dark and unsafe for women walking home.', 
    'लगभग 5 लगातार स्ट्रीट लाइट पोल काम नहीं कर रहे हैं, जिससे घर जाने वाली महिलाओं के लिए यह खंड पूरी तरह से अंधेरा और असुरक्षित हो गया है।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'medium', 
    'submitted', 
    'lmc', 
    26.8467, 
    80.9462, 
    'Hazratganj, Lucknow', 
    'user-30', 
    'Abhishek Mishra', 
    '+91 9837037018', 
    'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&h=400&fit=crop', 
    'AI auto-summary for dark street stretch behind gpo in Hazratganj.', 
    'Hazratganj में जीपीओ के पीछे अंधेरा सड़क खंड का स्व-निर्मित सारांश।', 
    0.87, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-032-457', 
    'Flickering street lights near Marine Drive', 
    'मरीन ड्राइव के पास टिमटिमाती स्ट्रीट लाइटें', 
    'Multiple street lights on the bypass road are flickering constantly, causing visibility issues for evening joggers and drivers.', 
    'बाईपास रोड पर कई स्ट्रीट लाइटें लगातार टिमटिमा रही हैं, जिससे शाम के धावकों और वाहन चालकों के लिए दृश्यता की समस्या हो रही है।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'low', 
    'department_assigned', 
    'lmc', 
    26.857, 
    80.9765, 
    'Gomti Nagar, Lucknow', 
    'user-31', 
    'Rajesh Pandey', 
    '+91 9838271585', 
    'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&h=400&fit=crop', 
    'AI auto-summary for flickering street lights near marine drive in Gomti Nagar.', 
    'Gomti Nagar में मरीन ड्राइव के पास टिमटिमाती स्ट्रीट लाइटें का स्व-निर्मित सारांश।', 
    0.88, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-033-474', 
    'Broken street light dome in Sector F', 
    'सेक्टर एफ में टूटी हुई स्ट्रीट लाइट गुंबद', 
    'The protective casing and LED bulb of the street light pole near post office are broken due to falling tree branch.', 
    'पेड़ की शाखा गिरने के कारण डाकघर के पास स्ट्रीट लाइट पोल का सुरक्षात्मक आवरण और एलईडी बल्ब टूट गया है।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'low', 
    'officer_reviewing', 
    'lmc', 
    26.8839, 
    80.9339, 
    'Aliganj, Lucknow', 
    'user-32', 
    'Sunita Rao', 
    '+91 9839506152', 
    'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&h=400&fit=crop', 
    'AI auto-summary for broken street light dome in sector f in Aliganj.', 
    'Aliganj में सेक्टर एफ में टूटी हुई स्ट्रीट लाइट गुंबद का स्व-निर्मित सारांश।', 
    0.9, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-034-491', 
    'No street lights on Sector 12 bypass road', 
    'सेक्टर 12 बाईपास मार्ग पर कोई स्ट्रीट लाइट नहीं', 
    'The newly constructed bypass road has light poles installed but they have not been connected to the power line yet.', 
    'नवनिर्मित बाईपास रोड पर लाइट पोल स्थापित हैं लेकिन उन्हें अभी तक बिजली लाइन से नहीं जोड़ा गया है, जिससे अंधेरा रहता है।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'medium', 
    'resolved', 
    'lmc', 
    26.8887, 
    80.964, 
    'Indira Nagar, Lucknow', 
    'user-33', 
    'Fatima Zaidi', 
    '+91 9840740719', 
    'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&h=400&fit=crop', 
    'AI auto-summary for no street lights on sector 12 bypass road in Indira Nagar.', 
    'Indira Nagar में सेक्टर 12 बाईपास मार्ग पर कोई स्ट्रीट लाइट नहीं का स्व-निर्मित सारांश।', 
    0.91, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-035-508', 
    'Non-functional lights in busy shopping lane', 
    'व्यस्त शॉपिंग गली में गैर-कार्यात्मक लाइटें', 
    'The central shopping lane has no working street lights, forcing shop owners to shut early or rely on backup generators.', 
    'केंद्रीय शॉपिंग लेन में कोई भी स्ट्रीट लाइट काम नहीं कर रही है, जिससे दुकान मालिकों को जल्दी बंद करने या बैकअप जनरेटर पर भरोसा करने के लिए मजबूर होना पड़ रहा है।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'medium', 
    'submitted', 
    'lmc', 
    26.8451, 
    80.9267, 
    'Aminabad, Lucknow', 
    'user-34', 
    'Karan Johar', 
    '+91 9841975286', 
    'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&h=400&fit=crop', 
    'AI auto-summary for non-functional lights in busy shopping lane in Aminabad.', 
    'Aminabad में व्यस्त शॉपिंग गली में गैर-कार्यात्मक लाइटें का स्व-निर्मित सारांश।', 
    0.92, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Smt. Neha Tripathi'
  ),
  (
    'JM-2026-036-525', 
    'Unauthorized floor construction in residential zone', 
    'आवासीय क्षेत्र में अनधिकृत मंजिल का निर्माण', 
    'A builder is constructing a 4th floor in a residential colony that is only approved for 2 floors, violating structural regulations.', 
    'एक बिल्डर एक आवासीय कॉलोनी में चौथी मंजिल का निर्माण कर रहा है जो केवल 2 मंजिलों के लिए स्वीकृत है, जो संरचनात्मक नियमों का उल्लंघन है।', 
    'Illegal Construction', 
    'अवैध निर्माण', 
    'medium', 
    'department_assigned', 
    'municipal-authority', 
    26.8582, 
    80.9777, 
    'Gomti Nagar, Lucknow', 
    'user-10', 
    'Vikram Rathore', 
    '+91 9843209853', 
    'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&h=400&fit=crop', 
    'AI auto-summary for unauthorized floor construction in residential zone in Gomti Nagar.', 
    'Gomti Nagar में आवासीय क्षेत्र में अनधिकृत मंजिल का निर्माण का स्व-निर्मित सारांश।', 
    0.94, 
    '{"trustLevel":"medium","spamProbability":0.35,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.65, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-037-542', 
    'Commercial shop being built in public park area', 
    'सार्वजनिक पार्क क्षेत्र में बनाई जा रही व्यावसायिक दुकान', 
    'Part of the public park boundary wall has been demolished to construct a commercial kiosk without permission.', 
    'अधिकारियों की अनुमति के बिना व्यावसायिक कियोस्क के निर्माण के लिए सार्वजनिक पार्क की सीमा की दीवार के हिस्से को ध्वस्त कर दिया गया है।', 
    'Illegal Construction', 
    'अवैध निर्माण', 
    'high', 
    'officer_reviewing', 
    'municipal-authority', 
    26.8851, 
    80.9351, 
    'Aliganj, Lucknow', 
    'user-11', 
    'Divya Joshi', 
    '+91 9844444420', 
    'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&h=400&fit=crop', 
    'AI auto-summary for commercial shop being built in public park area in Aliganj.', 
    'Aliganj में सार्वजनिक पार्क क्षेत्र में बनाई जा रही व्यावसायिक दुकान का स्व-निर्मित सारांश।', 
    0.95, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-038-559', 
    'Illegal building extension blocking service lane', 
    'सेवा मार्ग को अवरुद्ध करने वाला अवैध भवन विस्तार', 
    'A restaurant owner has constructed a permanent concrete extension that extends 5 feet into the narrow service lane.', 
    'एक रेस्तरां मालिक ने एक स्थायी कंक्रीट विस्तार का निर्माण किया है जो संकीर्ण सेवा गली में 5 फीट तक फैला हुआ है, जिससे यातायात बाधित हो रहा है।', 
    'Illegal Construction', 
    'अवैध निर्माण', 
    'medium', 
    'resolved', 
    'municipal-authority', 
    26.8448, 
    80.9443, 
    'Hazratganj, Lucknow', 
    'user-12', 
    'Mohd Sajid', 
    '+91 9845678987', 
    'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&h=400&fit=crop', 
    'AI auto-summary for illegal building extension blocking service lane in Hazratganj.', 
    'Hazratganj में सेवा मार्ग को अवरुद्ध करने वाला अवैध भवन विस्तार का स्व-निर्मित सारांश।', 
    0.96, 
    '{"trustLevel":"low","spamProbability":0.82,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.18, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-039-576', 
    'Basement excavation without safety retaining walls', 
    'सुरक्षा दीवारों के बिना बेसमेंट की खुदाई', 
    'A deep basement is being excavated next to residential houses without retaining walls, risking structural collapse of neighboring properties.', 
    'आवासीय घरों के बगल में बिना रिटेनिंग दीवारों के एक गहरे बेसमेंट की खुदाई की जा रही है, जिससे पड़ोसी संपत्तियों के गिरने का खतरा है।', 
    'Illegal Construction', 
    'अवैध निर्माण', 
    'high', 
    'submitted', 
    'municipal-authority', 
    26.8862, 
    80.9615, 
    'Indira Nagar, Lucknow', 
    'user-13', 
    'Pradeep Sen', 
    '+91 9846913554', 
    'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&h=400&fit=crop', 
    'AI auto-summary for basement excavation without safety retaining walls in Indira Nagar.', 
    'Indira Nagar में सुरक्षा दीवारों के बिना बेसमेंट की खुदाई का स्व-निर्मित सारांश।', 
    0.97, 
    '{"trustLevel":"medium","spamProbability":0.38,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.62, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-040-593', 
    'Unlicensed temporary shops blocking emergency exit', 
    'आपातकालीन निकास को अवरुद्ध करने वाली बिना लाइसेंस की अस्थायी दुकानें', 
    'Temporary steel structures are being constructed in the narrow fire access lane of the central market without approval.', 
    'बिना मंजूरी के केंद्रीय बाजार के संकीर्ण अग्नि पहुंच मार्ग में अस्थायी स्टील संरचनाओं का निर्माण किया जा रहा है।', 
    'Illegal Construction', 
    'अवैध निर्माण', 
    'high', 
    'department_assigned', 
    'municipal-authority', 
    26.8426, 
    80.9242, 
    'Aminabad, Lucknow', 
    'user-14', 
    'Pooja Vashisht', 
    '+91 9848148121', 
    'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&h=400&fit=crop', 
    'AI auto-summary for unlicensed temporary shops blocking emergency exit in Aminabad.', 
    'Aminabad में आपातकालीन निकास को अवरुद्ध करने वाली बिना लाइसेंस की अस्थायी दुकानें का स्व-निर्मित सारांश।', 
    0.99, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-041-610', 
    'Footpath occupied by unauthorized street vendors', 
    'अनधिकृत रेहड़ी-पटरी वालों द्वारा कब्जा किया गया फुटपाथ', 
    'The entire footpath along the main road is occupied by unauthorized stalls, forcing pedestrians to walk on the busy road asphalt.', 
    'मुख्य सड़क के किनारे पूरा फुटपाथ अनधिकृत स्टालों के कब्जे में है, जिससे राहगीर व्यस्त सड़क के डामर पर चलने को मजबूर हैं।', 
    'Encroachment', 
    'अतिक्रमण', 
    'medium', 
    'officer_reviewing', 
    'municipal-authority', 
    26.8457, 
    80.9452, 
    'Hazratganj, Lucknow', 
    'user-15', 
    'Abhishek Mishra', 
    '+91 9849382688', 
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop', 
    'AI auto-summary for footpath occupied by unauthorized street vendors in Hazratganj.', 
    'Hazratganj में अनधिकृत रेहड़ी-पटरी वालों द्वारा कब्जा किया गया फुटपाथ का स्व-निर्मित सारांश।', 
    0.81, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-042-627', 
    'Commercial vehicle display blocking public sidewalk', 
    'सार्वजनिक फुटपाथ को अवरुद्ध करने वाला व्यावसायिक वाहन प्रदर्शन', 
    'A showroom is displaying cars and heavy equipment directly on the public sidewalk, completely blocking pedestrian access.', 
    'एक शोरूम सार्वजनिक फुटपाथ पर सीधे कारों और भारी उपकरणों का प्रदर्शन कर रहा है, जिससे पैदल यात्रियों की पहुंच पूरी तरह से अवरुद्ध हो गई है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'low', 
    'resolved', 
    'municipal-authority', 
    26.856, 
    80.9755, 
    'Gomti Nagar, Lucknow', 
    'user-16', 
    'Rajesh Pandey', 
    '+91 9850617255', 
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop', 
    'AI auto-summary for commercial vehicle display blocking public sidewalk in Gomti Nagar.', 
    'Gomti Nagar में सार्वजनिक फुटपाथ को अवरुद्ध करने वाला व्यावसायिक वाहन प्रदर्शन का स्व-निर्मित सारांश।', 
    0.82, 
    '{"trustLevel":"high","spamProbability":0.04,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.96, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-043-644', 
    'Illegal private parking lot on vacant public plot', 
    'खाली पड़े सार्वजनिक भूखंड पर अवैध निजी पार्किंग स्थल', 
    'A private agent has set up ropes and is charging unauthorized parking fees on a vacant government-owned plot near Kapoorthala.', 
    'एक निजी एजेंट ने रस्सियाँ स्थापित कर ली हैं और कपूरथला के पास एक खाली सरकारी भूखंड पर अनधिकृत पार्किंग शुल्क वसूल कर रहा है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'low', 
    'submitted', 
    'municipal-authority', 
    26.8829, 
    80.9329, 
    'Aliganj, Lucknow', 
    'user-17', 
    'Sunita Rao', 
    '+91 9851851822', 
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop', 
    'AI auto-summary for illegal private parking lot on vacant public plot in Aliganj.', 
    'Aliganj में खाली पड़े सार्वजनिक भूखंड पर अवैध निजी पार्किंग स्थल का स्व-निर्मित सारांश।', 
    0.84, 
    '{"trustLevel":"high","spamProbability":0.05,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.95, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-044-661', 
    'Permanent ramps built over open drain covers', 
    'खुले नाले के ढक्कनों पर बने स्थायी रैंप', 
    'Shop owners have constructed high concrete ramps extending over the public drains, preventing cleaning access.', 
    'दुकान मालिकों ने सार्वजनिक नालों के ऊपर ऊंचे कंक्रीट के रैंप बना लिए हैं, जिससे सफाई कर्मचारियों को सफाई करने से रोका जा रहा है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'medium', 
    'department_assigned', 
    'municipal-authority', 
    26.8877, 
    80.963, 
    'Indira Nagar, Lucknow', 
    'user-18', 
    'Fatima Zaidi', 
    '+91 9853086389', 
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop', 
    'AI auto-summary for permanent ramps built over open drain covers in Indira Nagar.', 
    'Indira Nagar में खुले नाले के ढक्कनों पर बने स्थायी रैंप का स्व-निर्मित सारांश।', 
    0.85, 
    '{"trustLevel":"high","spamProbability":0.05,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.95, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-045-678', 
    'Hawkers permanently blocking main market crossing', 
    'मुख्य बाजार चौराहे को स्थायी रूप से अवरुद्ध करने वाले फेरीवाले', 
    'Illegal cart vendors are permanently stationed at the junction, causing severe traffic jams and blocking ambulance movement.', 
    'अवैध ठेला विक्रेता स्थायी रूप से जंक्शन पर तैनात हैं, जिससे भारी ट्रैफिक जाम हो रहा है और व्यस्त घंटों के दौरान एम्बुलेंस की आवाजाही अवरुद्ध हो रही है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'high', 
    'officer_reviewing', 
    'municipal-authority', 
    26.8441, 
    80.9257, 
    'Aminabad, Lucknow', 
    'user-19', 
    'Karan Johar', 
    '+91 9854320956', 
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop', 
    'AI auto-summary for hawkers permanently blocking main market crossing in Aminabad.', 
    'Aminabad में मुख्य बाजार चौराहे को स्थायी रूप से अवरुद्ध करने वाले फेरीवाले का स्व-निर्मित सारांश।', 
    0.86, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Deepak Gupta'
  ),
  (
    'JM-2026-046-695', 
    'Bribe demanded for birth certificate verification', 
    'जन्म प्रमाण पत्र सत्यापन के लिए रिश्वत की मांग', 
    'An official at the local ward desk is demanding a bribe of 2000 INR to process and verify the submitted birth certificate.', 
    'स्थानीय वार्ड डेस्क के एक अधिकारी ने प्रस्तुत जन्म प्रमाण पत्र दस्तावेज को संसाधित करने और सत्यापित करने के लिए 2000 रुपये की रिश्वत की मांग की है।', 
    'Corruption', 
    'भ्रष्टाचार / रिश्वत', 
    'medium', 
    'resolved', 
    'anti-corruption', 
    26.8472, 
    80.9467, 
    'Hazratganj, Lucknow', 
    'user-20', 
    'Vikram Rathore', 
    '+91 9855555523', 
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop', 
    'AI auto-summary for bribe demanded for birth certificate verification in Hazratganj.', 
    'Hazratganj में जन्म प्रमाण पत्र सत्यापन के लिए रिश्वत की मांग का स्व-निर्मित सारांश।', 
    0.88, 
    '{"trustLevel":"high","spamProbability":0,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    1, 
    'Shri Arvind Mishra'
  ),
  (
    'JM-2026-047-712', 
    'Favored allocation of commercial cart licenses', 
    'व्यावसायिक कार्ट लाइसेंस का पसंदीदा आवंटन', 
    'Local supervisor is allegedly taking cash bribes under-the-table to allocate prime street vendor spots to select unauthorized hawkers.', 
    'स्थानीय पर्यवेक्षक कथित तौर पर चुनिंदा अनधिकृत फेरीवालों को प्रमुख स्ट्रीट वेंडर स्पॉट आवंटित करने के लिए नकद रिश्वत ले रहे हैं।', 
    'Corruption', 
    'भ्रष्टाचार / रिश्वत', 
    'medium', 
    'submitted', 
    'anti-corruption', 
    26.8575, 
    80.977, 
    'Gomti Nagar, Lucknow', 
    'user-21', 
    'Divya Joshi', 
    '+91 9856790090', 
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop', 
    'AI auto-summary for favored allocation of commercial cart licenses in Gomti Nagar.', 
    'Gomti Nagar में व्यावसायिक कार्ट लाइसेंस का पसंदीदा आवंटन का स्व-निर्मित सारांश।', 
    0.89, 
    '{"trustLevel":"low","spamProbability":0.91,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.09, 
    'Shri Arvind Mishra'
  ),
  (
    'JM-2026-048-729', 
    'Ransom demand for releasing seized shop tools', 
    'जब्त किए गए दुकान के उपकरण छोड़ने के लिए रिश्वत की मांग', 
    'Municipal squad demanded cash without invoice to return display tables and tools seized during the routine clearance drive.', 
    'नगर निगम के दस्ते ने नियमित निकासी अभियान के दौरान जब्त किए गए डिस्प्ले टेबल और उपकरण वापस करने के लिए बिना चालान के नकद की मांग की।', 
    'Corruption', 
    'भ्रष्टाचार / रिश्वत', 
    'high', 
    'department_assigned', 
    'anti-corruption', 
    26.8844, 
    80.9344, 
    'Aliganj, Lucknow', 
    'user-22', 
    'Mohd Sajid', 
    '+91 9858024657', 
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop', 
    'AI auto-summary for ransom demand for releasing seized shop tools in Aliganj.', 
    'Aliganj में जब्त किए गए दुकान के उपकरण छोड़ने के लिए रिश्वत की मांग का स्व-निर्मित सारांश।', 
    0.9, 
    '{"trustLevel":"medium","spamProbability":0.47,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.53, 
    'Shri Arvind Mishra'
  ),
  (
    'JM-2026-049-746', 
    'Corruption in sewer pipeline quality inspection', 
    'सीवर पाइपलाइन गुणवत्ता निरीक्षण में भ्रष्टाचार', 
    'Contractor is using inferior quality clay pipes, and municipal inspectors are allegedly bribed to sign off on completion.', 
    'ठेकेदार घटिया गुणवत्ता वाले मिट्टी के पाइप का उपयोग कर रहा है, और नगर निगम निरीक्षकों को कथित तौर पर पूर्णता प्रमाणपत्रों पर हस्ताक्षर करने के लिए रिश्वत दी जाती है।', 
    'Corruption', 
    'भ्रष्टाचार / रिश्वत', 
    'high', 
    'officer_reviewing', 
    'anti-corruption', 
    26.8892, 
    80.9645, 
    'Indira Nagar, Lucknow', 
    'user-23', 
    'Pradeep Sen', 
    '+91 9859259224', 
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop', 
    'AI auto-summary for corruption in sewer pipeline quality inspection in Indira Nagar.', 
    'Indira Nagar में सीवर पाइपलाइन गुणवत्ता निरीक्षण में भ्रष्टाचार का स्व-निर्मित सारांश।', 
    0.91, 
    '{"trustLevel":"high","spamProbability":0.01,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.99, 
    'Shri Arvind Mishra'
  ),
  (
    'JM-2026-050-763', 
    'Bribe requested for trade license renewal', 
    'व्यापार लाइसेंस नवीनीकरण के लिए रिश्वत का अनुरोध', 
    'Clerks are intentionally delaying the trade license renewal requests of shop owners until an illegal payment is made.', 
    'लिपिक जानबूझकर दुकान मालिकों के व्यापार लाइसेंस नवीनीकरण अनुरोधों में देरी कर रहे हैं जब तक कि एक अवैध भुगतान नहीं किया जाता है।', 
    'Corruption', 
    'भ्रष्टाचार / रिश्वत', 
    'medium', 
    'resolved', 
    'anti-corruption', 
    26.8456, 
    80.9272, 
    'Aminabad, Lucknow', 
    'user-24', 
    'Pooja Vashisht', 
    '+91 9860493791', 
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop', 
    'AI auto-summary for bribe requested for trade license renewal in Aminabad.', 
    'Aminabad में व्यापार लाइसेंस नवीनीकरण के लिए रिश्वत का अनुरोध का स्व-निर्मित सारांश।', 
    0.93, 
    '{"trustLevel":"low","spamProbability":0.94,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.06, 
    'Shri Arvind Mishra'
  ),
  (
    'JM-2026-051-780', 
    'Dengue breeding site at abandoned builder plot', 
    'परित्यक्त बिल्डर भूखंड पर डेंगू प्रजनन स्थल', 
    'Rainwater has accumulated in a large open foundation hole for months, creating a mosquito breeding ground. Multiple dengue cases reported.', 
    'महीनों से एक बड़े खुले फाउंडेशन के गड्ढे में बारिश का पानी जमा हो गया है, जिससे मच्छरों के पनपने की जगह बन गई है। कई डेंगू मामलों की सूचना मिली है।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'high', 
    'submitted', 
    'health-dept', 
    26.8853, 
    80.9353, 
    'Aliganj, Lucknow', 
    'user-25', 
    'Abhishek Mishra', 
    '+91 9861728358', 
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop', 
    'AI auto-summary for dengue breeding site at abandoned builder plot in Aliganj.', 
    'Aliganj में परित्यक्त बिल्डर भूखंड पर डेंगू प्रजनन स्थल का स्व-निर्मित सारांश।', 
    0.94, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Dr. Sanjay Pandey'
  ),
  (
    'JM-2026-052-797', 
    'Medical waste dumped behind community clinic', 
    'सामुदायिक क्लिनिक के पीछे फेंका गया चिकित्सा कचरा', 
    'Used syringes, cotton swabs, and expired medicine bottles are dumped in an open general bin outside, easily accessible to street dogs.', 
    'इस्तेमाल की गई सीरिंज, कॉटन स्वैब और एक्सपायर्ड दवा की बोतलें बाहर एक खुले सामान्य डिब्बे में फेंक दी जाती हैं, जो आवारा कुत्तों के लिए आसानी से सुलभ हैं।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'high', 
    'department_assigned', 
    'health-dept', 
    26.855, 
    80.9745, 
    'Gomti Nagar, Lucknow', 
    'user-26', 
    'Rajesh Pandey', 
    '+91 9862962925', 
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop', 
    'AI auto-summary for medical waste dumped behind community clinic in Gomti Nagar.', 
    'Gomti Nagar में सामुदायिक क्लिनिक के पीछे फेंका गया चिकित्सा कचरा का स्व-निर्मित सारांश।', 
    0.95, 
    '{"trustLevel":"high","spamProbability":0.02,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.98, 
    'Dr. Sanjay Pandey'
  ),
  (
    'JM-2026-053-814', 
    'Unhygienic food preparation at street stalls', 
    'सड़क के स्टालों पर अस्वास्थ्यकर भोजन तैयार करना', 
    'Vendors near the market are preparing food using stagnant tap water and raw ingredients exposed to heavy road dust.', 
    'बाजार के पास विक्रेता स्थिर नल के पानी और भारी सड़क की धूल और मक्खियों के संपर्क में आने वाली कच्ची सामग्री का उपयोग करके भोजन तैयार कर रहे हैं।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'medium', 
    'officer_reviewing', 
    'health-dept', 
    26.8453, 
    80.9448, 
    'Hazratganj, Lucknow', 
    'user-27', 
    'Sunita Rao', 
    '+91 9864197492', 
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop', 
    'AI auto-summary for unhygienic food preparation at street stalls in Hazratganj.', 
    'Hazratganj में सड़क के स्टालों पर अस्वास्थ्यकर भोजन तैयार करना का स्व-निर्मित सारांश।', 
    0.97, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Dr. Sanjay Pandey'
  ),
  (
    'JM-2026-054-831', 
    'Stagnant sewage water in Sector D residential lane', 
    'सेक्टर डी आवासीय गली में स्थिर सीवेज का पानी', 
    'A broken sewer pipe has flooded the residential lane, creating an extremely unhygienic environment with severe foul odor.', 
    'टूटी हुई सीवर लाइन ने आवासीय गली में पानी भर दिया है, जिससे तीव्र दुर्गंध के साथ एक अत्यंत अस्वास्थ्यकर वातावरण बन गया है।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'high', 
    'resolved', 
    'health-dept', 
    26.8867, 
    80.962, 
    'Indira Nagar, Lucknow', 
    'user-28', 
    'Fatima Zaidi', 
    '+91 9865432059', 
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop', 
    'AI auto-summary for stagnant sewage water in sector d residential lane in Indira Nagar.', 
    'Indira Nagar में सेक्टर डी आवासीय गली में स्थिर सीवेज का पानी का स्व-निर्मित सारांश।', 
    0.98, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Dr. Sanjay Pandey'
  ),
  (
    'JM-2026-055-848', 
    'Lack of public toilet cleaning and sanitization', 
    'सार्वजनिक शौचालय की सफाई और स्वच्छता का अभाव', 
    'The main community toilet is in a completely blocked, unusable state with no running water, creating a major public health hazard.', 
    'मुख्य सामुदायिक शौचालय पूरी तरह से अवरुद्ध, अनुपयोगी स्थिति में है और बहता पानी नहीं है, जिससे सार्वजनिक स्वास्थ्य के लिए एक बड़ा खतरा पैदा हो गया है।', 
    'Public Health', 
    'जन स्वास्थ्य', 
    'medium', 
    'submitted', 
    'health-dept', 
    26.8431, 
    80.9247, 
    'Aminabad, Lucknow', 
    'user-29', 
    'Karan Johar', 
    '+91 9866666626', 
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop', 
    'AI auto-summary for lack of public toilet cleaning and sanitization in Aminabad.', 
    'Aminabad में सार्वजनिक शौचालय की सफाई और स्वच्छता का अभाव का स्व-निर्मित सारांश।', 
    0.8, 
    '{"trustLevel":"high","spamProbability":0.03,"reviewedByOfficer":false,"officerVerdict":null}'::jsonb, 
    0.97, 
    'Dr. Sanjay Pandey'
  );

-- Seed timeline updates
INSERT INTO public.complaint_updates (complaint_id, status, message, message_hi)
VALUES
  ('JM-2026-001-999', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-001-999', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-002-888', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-002-888', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-002-888', 'officer_reviewing', 'Officer Smt. Neha Tripathi has begun reviewing the grievance.', 'अधिकारी Smt. Neha Tripathi ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-002-888', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-003-777', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-004-666', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-004-666', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-005-555', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-006-444', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-006-444', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-006-444', 'officer_reviewing', 'Officer Shri Rajesh Kumar has begun reviewing the grievance.', 'अधिकारी Shri Rajesh Kumar ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-006-444', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-007-333', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-007-333', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-008-222', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-009-111', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-009-111', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-009-111', 'officer_reviewing', 'Officer Shri Rajesh Kumar has begun reviewing the grievance.', 'अधिकारी Shri Rajesh Kumar ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-009-111', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-010-000', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-010-000', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-011-100', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-012-117', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-012-117', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-013-134', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-013-134', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-013-134', 'officer_reviewing', 'Officer Shri Rajesh Kumar has begun reviewing the grievance.', 'अधिकारी Shri Rajesh Kumar ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-014-151', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-014-151', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-014-151', 'officer_reviewing', 'Officer Shri Rajesh Kumar has begun reviewing the grievance.', 'अधिकारी Shri Rajesh Kumar ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-014-151', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-015-168', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-016-185', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-016-185', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-017-202', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-017-202', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-017-202', 'officer_reviewing', 'Officer Smt. Priya Sharma has begun reviewing the grievance.', 'अधिकारी Smt. Priya Sharma ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-018-219', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-018-219', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-018-219', 'officer_reviewing', 'Officer Smt. Priya Sharma has begun reviewing the grievance.', 'अधिकारी Smt. Priya Sharma ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-018-219', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-019-236', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-020-253', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-020-253', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-021-270', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-021-270', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-021-270', 'officer_reviewing', 'Officer Shri Amit Verma has begun reviewing the grievance.', 'अधिकारी Shri Amit Verma ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-022-287', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-022-287', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-022-287', 'officer_reviewing', 'Officer Shri Amit Verma has begun reviewing the grievance.', 'अधिकारी Shri Amit Verma ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-022-287', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-023-304', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-024-321', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-024-321', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-025-338', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-025-338', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-025-338', 'officer_reviewing', 'Officer Shri Amit Verma has begun reviewing the grievance.', 'अधिकारी Shri Amit Verma ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-026-355', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-026-355', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-026-355', 'officer_reviewing', 'Officer Shri Vikram Singh has begun reviewing the grievance.', 'अधिकारी Shri Vikram Singh ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-026-355', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-027-372', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-028-389', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-028-389', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-029-406', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-029-406', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-029-406', 'officer_reviewing', 'Officer Shri Vikram Singh has begun reviewing the grievance.', 'अधिकारी Shri Vikram Singh ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-030-423', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-030-423', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-030-423', 'officer_reviewing', 'Officer Shri Vikram Singh has begun reviewing the grievance.', 'अधिकारी Shri Vikram Singh ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-030-423', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-031-440', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-032-457', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-032-457', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-033-474', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-033-474', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-033-474', 'officer_reviewing', 'Officer Smt. Neha Tripathi has begun reviewing the grievance.', 'अधिकारी Smt. Neha Tripathi ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-034-491', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-034-491', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-034-491', 'officer_reviewing', 'Officer Smt. Neha Tripathi has begun reviewing the grievance.', 'अधिकारी Smt. Neha Tripathi ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-034-491', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-035-508', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-036-525', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-036-525', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-037-542', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-037-542', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-037-542', 'officer_reviewing', 'Officer Shri Deepak Gupta has begun reviewing the grievance.', 'अधिकारी Shri Deepak Gupta ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-038-559', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-038-559', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-038-559', 'officer_reviewing', 'Officer Shri Deepak Gupta has begun reviewing the grievance.', 'अधिकारी Shri Deepak Gupta ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-038-559', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-039-576', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-040-593', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-040-593', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-041-610', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-041-610', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-041-610', 'officer_reviewing', 'Officer Shri Deepak Gupta has begun reviewing the grievance.', 'अधिकारी Shri Deepak Gupta ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-042-627', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-042-627', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-042-627', 'officer_reviewing', 'Officer Shri Deepak Gupta has begun reviewing the grievance.', 'अधिकारी Shri Deepak Gupta ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-042-627', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-043-644', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-044-661', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-044-661', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-045-678', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-045-678', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-045-678', 'officer_reviewing', 'Officer Shri Deepak Gupta has begun reviewing the grievance.', 'अधिकारी Shri Deepak Gupta ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-046-695', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-046-695', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-046-695', 'officer_reviewing', 'Officer Shri Arvind Mishra has begun reviewing the grievance.', 'अधिकारी Shri Arvind Mishra ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-046-695', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-047-712', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-048-729', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-048-729', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-049-746', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-049-746', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-049-746', 'officer_reviewing', 'Officer Shri Arvind Mishra has begun reviewing the grievance.', 'अधिकारी Shri Arvind Mishra ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-050-763', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-050-763', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-050-763', 'officer_reviewing', 'Officer Shri Arvind Mishra has begun reviewing the grievance.', 'अधिकारी Shri Arvind Mishra ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-050-763', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-051-780', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-052-797', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-052-797', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-053-814', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-053-814', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-053-814', 'officer_reviewing', 'Officer Dr. Sanjay Pandey has begun reviewing the grievance.', 'अधिकारी Dr. Sanjay Pandey ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-054-831', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-054-831', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-054-831', 'officer_reviewing', 'Officer Dr. Sanjay Pandey has begun reviewing the grievance.', 'अधिकारी Dr. Sanjay Pandey ने शिकायत की समीक्षा शुरू कर दी है।'),
  ('JM-2026-054-831', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-055-848', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।');
