-- Seed data for complaints
INSERT INTO public.complaints (id, title, title_hi, description, description_hi, category, category_hi, priority, status, department_id, latitude, longitude, area, citizen_id, citizen_name, citizen_phone, image_url, ai_summary, ai_summary_hi, ai_confidence, trust_analysis, trust_score, assigned_officer)
VALUES
  (
    'JM-2026-001-999', 
    'Massive garbage pile near bus stand', 
    'बस स्टैंड के पास भारी कचरे का ढेर', 
    'There is a huge pile of garbage that has not been collected for a week. The smell is unbearable and it is becoming a health hazard.', 
    'बस स्टैंड के पास एक सप्ताह से कचरा नहीं उठाया गया है। बदबू असहनीय है और यह स्वास्थ्य के लिए खतरा बन रहा है।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'high', 
    'department_assigned', 
    'nagar-nigam', 
    26.8500, 
    80.9500, 
    'Alambagh, Lucknow', 
    'user-1', 
    'Aman Singh', 
    '+91 98765 43210', 
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&h=400&fit=crop',
    'Severe sanitation hazard reported near Alambagh bus stand.', 
    'आलमबाग बस स्टैंड के पास गंभीर स्वच्छता खतरा।', 
    0.95, 
    '{"trustLevel": "high", "spamProbability": 0.05}', 
    0.95, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-002-888', 
    'Street light not working in sector 4', 
    'सेक्टर 4 में स्ट्रीट लाइट काम नहीं कर रही', 
    'Street light has been broken for 3 days, causing accidents in the dark.', 
    '3 दिन से स्ट्रीट लाइट खराब है, जिससे अंधेरे में दुर्घटनाएं हो रही हैं।', 
    'Street Light', 
    'स्ट्रीट लाइट', 
    'medium', 
    'resolved', 
    'lesa', 
    26.8400, 
    80.9600, 
    'Gomti Nagar, Lucknow', 
    'user-2', 
    'Priya Verma', 
    '+91 87654 32109', 
    'https://images.unsplash.com/photo-1517789490516-fb46487e49ba?w=600&h=400&fit=crop',
    'Street light outage reported in Gomti Nagar.', 
    'गोमती नगर में स्ट्रीट लाइट खराब होने की रिपोर्ट।', 
    0.92, 
    '{"trustLevel": "high", "spamProbability": 0.02}', 
    0.98, 
    'Smt. Meena Devi'
  ),
  (
    'JM-2026-003-777', 
    'Major water pipe burst on Main Road', 
    'मुख्य मार्ग पर पानी की पाइपलाइन फटी', 
    'A major water pipeline has burst, causing severe waterlogging and wastage of clean drinking water.', 
    'एक प्रमुख पानी की पाइपलाइन फट गई है, जिससे भारी जलभराव और पीने के साफ पानी की बर्बादी हो रही है।', 
    'Water Supply', 
    'जल आपूर्ति', 
    'high', 
    'submitted', 
    'jal-sansthan', 
    26.8600, 
    80.9400, 
    'Hazratganj, Lucknow', 
    'user-3', 
    'Rahul Sharma', 
    '+91 91234 56780', 
    'https://images.unsplash.com/photo-1541888075765-a81062b08a54?w=600&h=400&fit=crop',
    'Major pipeline burst causing waterlogging in Hazratganj.', 
    'हजरतगंज में पाइपलाइन फटने से जलभराव की समस्या।', 
    0.96, 
    '{"trustLevel": "high", "spamProbability": 0.01}', 
    0.99, 
    'Shri Anil Dubey'
  ),
  (
    'JM-2026-004-666', 
    'Pothole causing accidents', 
    'गड्ढे के कारण हो रही दुर्घटनाएं', 
    'Large pothole in the middle of the road has caused two bike accidents today alone. Please fix urgently.', 
    'सड़क के बीच में बड़े गड्ढे के कारण आज ही दो बाइक दुर्घटनाएं हुई हैं। कृपया तत्काल ठीक करें।', 
    'Roads / Potholes', 
    'सड़कें / गड्ढे', 
    'high', 
    'department_assigned', 
    'pwd', 
    26.8700, 
    80.9300, 
    'Indira Nagar, Lucknow', 
    'user-4', 
    'Sneha Gupta', 
    '+91 99887 76655', 
    'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&h=400&fit=crop',
    'Dangerous pothole causing accidents in Indira Nagar.', 
    'इंदिरा नगर में गड्ढे के कारण दुर्घटनाओं की रिपोर्ट।', 
    0.94, 
    '{"trustLevel": "high", "spamProbability": 0.04}', 
    0.96, 
    'Shri R. K. Singh'
  ),
  (
    'JM-2026-005-555', 
    'Stray dogs attacking pedestrians', 
    'आवारा कुत्ते राहगीरों पर हमला कर रहे हैं', 
    'A pack of stray dogs is acting aggressively and has bitten a child yesterday. Immediate action required.', 
    'आवारा कुत्तों का एक झुंड आक्रामक हो रहा है और कल एक बच्चे को काट लिया है। तत्काल कार्रवाई की आवश्यकता है।', 
    'Animal Control', 
    'पशु नियंत्रण', 
    'medium', 
    'submitted', 
    'animal-control', 
    26.8550, 
    80.9650, 
    'Mahanagar, Lucknow', 
    'user-5', 
    'Vikram Singh', 
    '+91 88776 65544', 
    'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=600&h=400&fit=crop',
    'Aggressive stray dogs reported in Mahanagar.', 
    'महानगर में आक्रामक आवारा कुत्तों की शिकायत।', 
    0.88, 
    '{"trustLevel": "medium", "spamProbability": 0.1}', 
    0.85, 
    'Dr. Vivek Sharma'
  ),
  (
    'JM-2026-006-444', 
    'Open manhole on footpath', 
    'फुटपाथ पर खुला मैनहोल', 
    'The manhole cover is missing near the park gate. It is very dangerous for children playing nearby.', 
    'पार्क के गेट के पास मैनहोल का ढक्कन गायब है। यह पास में खेलने वाले बच्चों के लिए बहुत खतरनाक है।', 
    'Public Infrastructure', 
    'सार्वजनिक बुनियादी ढांचा', 
    'high', 
    'resolved', 
    'nagar-nigam', 
    26.8450, 
    80.9350, 
    'Aashiana, Lucknow', 
    'user-6', 
    'Kavita Tiwari', 
    '+91 77665 54433', 
    'https://images.unsplash.com/photo-1621245781440-101f3db3e6ba?w=600&h=400&fit=crop',
    'Dangerous open manhole near park in Aashiana.', 
    'आशियाना में पार्क के पास खतरनाक खुला मैनहोल।', 
    0.97, 
    '{"trustLevel": "high", "spamProbability": 0.01}', 
    0.99, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-007-333', 
    'Illegal construction blocking drain', 
    'अवैध निर्माण से नाला बंद', 
    'Someone is building a ramp over the public drain, which is causing sewage water to overflow onto the street.', 
    'कोई सार्वजनिक नाले के ऊपर रैंप बना रहा है, जिससे सीवर का पानी सड़क पर बह रहा है।', 
    'Encroachment', 
    'अतिक्रमण', 
    'low', 
    'department_assigned', 
    'nagar-nigam', 
    26.8350, 
    80.9550, 
    'Rajajipuram, Lucknow', 
    'user-7', 
    'Mohammad Arif', 
    '+91 66554 43322', 
    'https://images.unsplash.com/photo-1504307651254-35680f356f12?w=600&h=400&fit=crop',
    'Drain blocked by illegal construction in Rajajipuram.', 
    'राजाजीपुरम में अवैध निर्माण के कारण नाला अवरुद्ध।', 
    0.91, 
    '{"trustLevel": "high", "spamProbability": 0.08}', 
    0.92, 
    'Smt. Sunita Yadav'
  ),
  (
    'JM-2026-008-222', 
    'Dead animal on the road', 
    'सड़क पर मृत जानवर', 
    'A dead cow is lying on the bypass road since morning. Please send a vehicle to pick it up.', 
    'सुबह से बाईपास रोड पर एक मृत गाय पड़ी है। कृपया इसे उठाने के लिए वाहन भेजें।', 
    'Garbage / Sanitation', 
    'कचरा / स्वच्छता', 
    'medium', 
    'submitted', 
    'nagar-nigam', 
    26.8800, 
    80.9200, 
    'Jankipuram, Lucknow', 
    'user-8', 
    'Alok Pandey', 
    '+91 55443 32211', 
    'https://images.unsplash.com/photo-1596781206132-75ebdb5952d4?w=600&h=400&fit=crop',
    'Dead animal removal requested in Jankipuram.', 
    'जानकीपुरम में मृत जानवर उठाने का अनुरोध।', 
    0.93, 
    '{"trustLevel": "high", "spamProbability": 0.03}', 
    0.97, 
    'Shri Rajesh Kumar'
  ),
  (
    'JM-2026-009-111', 
    'Park poorly maintained', 
    'पार्क का रखरखाव खराब है', 
    'The swings in the local park are broken and the grass has not been cut for months.', 
    'स्थानीय पार्क में झूले टूटे हुए हैं और महीनों से घास नहीं काटी गई है।', 
    'Parks & Recreation', 
    'पार्क और मनोरंजन', 
    'low', 
    'resolved', 
    'nagar-nigam', 
    26.8300, 
    80.9600, 
    'Vikas Nagar, Lucknow', 
    'user-9', 
    'Neha Singh', 
    '+91 44332 21100', 
    'https://images.unsplash.com/photo-1500367215255-0e0b2148b556?w=600&h=400&fit=crop',
    'Poor park maintenance and broken swings in Vikas Nagar.', 
    'विकास नगर में पार्क का खराब रखरखाव और टूटे झूले।', 
    0.85, 
    '{"trustLevel": "medium", "spamProbability": 0.15}', 
    0.80, 
    'Shri Sanjay Mishra'
  ),
  (
    'JM-2026-010-000', 
    'Live electric wire hanging low', 
    'बिजली का खुला तार नीचे लटक रहा है', 
    'A live electric wire has snapped and is hanging dangerously low near the school gate. Highly dangerous!', 
    'एक खुला बिजली का तार टूट गया है और स्कूल के गेट के पास खतरनाक रूप से नीचे लटक रहा है। अत्यधिक खतरनाक!', 
    'Electricity', 
    'बिजली', 
    'high', 
    'department_assigned', 
    'lesa', 
    26.8650, 
    80.9450, 
    'Chowk, Lucknow', 
    'user-10', 
    'Syed Ali', 
    '+91 33221 10099', 
    'https://images.unsplash.com/photo-1544257124-74bf5fbfe4b2?w=600&h=400&fit=crop',
    'Dangerous live wire hanging near school in Chowk.', 
    'चौक में स्कूल के पास लटकता हुआ खतरनाक खुला तार।', 
    0.98, 
    '{"trustLevel": "high", "spamProbability": 0.00}', 
    1.00, 
    'Smt. Meena Devi'
  );

-- Seed timeline updates
INSERT INTO public.complaint_updates (complaint_id, status, message, message_hi)
VALUES
  ('JM-2026-001-999', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-001-999', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-002-888', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-002-888', 'resolved', 'Issue resolved completely. Resolution verified by department.', 'समस्या का पूर्ण निवारण हो चुका है। विभाग द्वारा निवारण की पुष्टि की गई है।'),
  ('JM-2026-003-777', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-004-666', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-004-666', 'department_assigned', 'Routed to PWD for road repairs.', 'सड़क मरम्मत के लिए लोक निर्माण विभाग को भेजा गया।'),
  ('JM-2026-005-555', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-006-444', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-006-444', 'department_assigned', 'Routed to department automatically.', 'स्वचालित रूप से आवंटित।'),
  ('JM-2026-006-444', 'resolved', 'Manhole cover has been replaced.', 'मैनहोल का ढक्कन बदल दिया गया है।'),
  ('JM-2026-007-333', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-007-333', 'department_assigned', 'Routed to encroachment cell.', 'अतिक्रमण सेल को भेजा गया।'),
  ('JM-2026-008-222', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-009-111', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-009-111', 'resolved', 'Park cleaned and swings repaired.', 'पार्क की सफाई की गई और झूले की मरम्मत की गई।'),
  ('JM-2026-010-000', 'submitted', 'Complaint submitted successfully by citizen.', 'नागरिक द्वारा शिकायत सफलतापूर्वक दर्ज की गई।'),
  ('JM-2026-010-000', 'department_assigned', 'Priority routing to electricity department.', 'बिजली विभाग को प्राथमिकता से भेजा गया।');
